const {chromium}=require('playwright');
const S=__dirname,U=process.env.CELUS_URL||'http://localhost:4173';
(async()=>{const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:400,height:860},geolocation:{latitude:-23.5505,longitude:-46.6333},permissions:['geolocation']});
const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));
const log=(...a)=>console.log(...a);
const step=async(n,f)=>{try{await f()}catch(e){log('FAIL',n,e.message.split('\n')[0]);await p.screenshot({path:S+'/../../.teste-saida/falha-'+n+'.png'});}};
p.setDefaultTimeout(8000);
await step('entrar',async()=>{await p.goto(U+'/');await p.waitForURL('**/entrar');log('redirect ok');});
await step('menor',async()=>{await p.click('text=Criar conta');
await p.fill('#c-nome','Teste Menor');await p.fill('#c-email','menor@x.com');await p.fill('#c-senha','12345678');await p.fill('#c-nasc','2012-05-01');await p.check('#c-aceite');await p.click('button:has-text("Continuar")');
log('menor:', await p.textContent('h1'));});
await step('cadastro',async()=>{await p.click('text=Voltar ao início');await p.click('text=Criar conta');
await p.fill('#c-nome','Emanuelle Macedo');await p.fill('#c-email','emanuelle@x.com');await p.fill('#c-senha','12345678');await p.fill('#c-nasc','1990-05-01');await p.check('#c-aceite');await p.click('button:has-text("Continuar")');
await p.waitForURL('**/verificar');await p.setInputFiles('#v-doc',S+'/foto.jpg');await p.setInputFiles('#v-selfie',S+'/foto.jpg');await p.click('text=Enviar para verificação');
await p.waitForURL(U+'/');log('map:',await p.textContent('h1'));});
await step('reserva',async()=>{await p.fill('#busca','rede');log('busca rede:',await p.$$eval('.cartao .t',e=>e.map(x=>x.textContent)));
await p.click('.cartao >> nth=0');await p.click('button:has-text("Confirmar e pagar")');await p.click('text=Gerar Pix');await p.click('text=Simular Pix recebido');
await p.waitForURL('**/reserva/**');log('reserva:',await p.textContent('.eyebrow'));});
await step('timer',async()=>{await p.click('text=Simular conferência do código');await p.waitForURL('**/uso/**');
for(let i=0;i<5;i++) await p.click('text=Avançar 10 min');
log('alerta:',await p.textContent('.alerta'));
for(let i=0;i<4;i++) await p.click('text=Avançar 10 min');
log('alerta2:',await p.textContent('.alerta'));
await p.screenshot({path:S+'/t-timer.png'});});
await step('avaliar',async()=>{await p.click('text=Encerrar e sair');await p.waitForTimeout(300);
await p.click('.stars >> nth=0 >> button >> nth=4');await p.click('.stars >> nth=1 >> button >> nth=3');await p.click('.seg button:has-text("Sim")');await p.click('text=Enviar avaliação');
await p.waitForURL('**/perfil');log('saldo:',await p.textContent('.walletmini b'));});
await step('story',async()=>{await ctx.setGeolocation({latitude:-23.5505-0.9/110.574,longitude:-46.6333+0.3/(111.32*Math.cos(-23.5505*Math.PI/180))});
await p.goto(U+'/');await p.fill('#busca','vestiário');await p.click('.cartao >> nth=0');await p.waitForTimeout(1500);
await p.click('text=Estou aqui');await p.waitForTimeout(300);log('toast:',await p.textContent('.toast'));
await p.click('text=Postar story daqui');await p.setInputFiles('#s-foto',S+'/foto.jpg');await p.fill('#s-legenda','Teste');await p.click('text=Publicar story');await p.waitForTimeout(300);log('story toast:',await p.textContent('.toast'));});
await step('sema',async()=>{await p.goto(U+'/');await p.click('.sema');await p.click('.semaopt >> nth=0');log('sema:',await p.textContent('.toast'));await p.screenshot({path:S+'/t-mapa.png'});});
await step('chat',async()=>{await p.click('nav >> text=Chat');await p.click('text=Entendi, entrar na sala');await p.waitForTimeout(300);
await p.fill('#chat-msg','me liga 11 91234-5678');await p.click('.chatbar button');log('chat block:',await p.textContent('.toast'));
await p.fill('#chat-msg','Oi pessoal, alguém no vestiário?');await p.click('.chatbar button');await p.waitForTimeout(200);log('msgs:',await p.$$eval('.msg',e=>e.length));
await p.screenshot({path:S+'/t-chat.png'});});
await step('feed',async()=>{await p.click('nav >> text=Feed');log('feed posts:',await p.$$eval('.post',e=>e.length), 'stories:', await p.$$eval('.sto',e=>e.length));});
await step('anunciar',async()=>{await p.click('text=Rentabilizar');log('painel:',await p.textContent('h1'));
await p.click('nav >> text=Anunciar');await p.fill('#a-titulo','Varanda com rede teste');await p.setInputFiles('#a-fotos',S+'/foto.jpg');await p.fill('textarea >> nth=1','Feche o portão');await p.click('text=Enviar para aprovação');
await p.waitForURL('**/renda');log('status:',await p.textContent('.status'));});
await step('curadoria',async()=>{await p.click('nav >> text=Curadoria');log('cur:',await p.textContent('.lead'));
await p.click('text=Procurar');await p.click('nav >> text=Perfil');await p.check('.sumline.check input');
await p.click('text=Rentabilizar');await p.click('nav >> text=Curadoria');await p.click('button:has-text("Aprovar")');log('aprov:',await p.textContent('.toast'));});
await step('agenda',async()=>{await p.click('nav >> text=Painel');await p.click('text=Agenda');await p.fill('input[type=date]','2026-12-25');await p.click('text=Bloquear');await p.click('text=Salvar agenda');log('agenda:',await p.textContent('.toast'));
await p.click('nav >> text=Painel');await p.screenshot({path:S+'/t-painel.png',fullPage:true});});
await step('servico',async()=>{await p.click('text=Procurar');await p.fill('#busca','eletricista');await p.click('.cartao >> nth=0');await p.click('button:has-text("Chamar")');await p.click('text=Gerar Pix');await p.click('text=Simular Pix recebido');await p.waitForTimeout(9000);await p.click('text=Simular conferência do código');await p.waitForTimeout(300);log('servico:',await p.textContent('.eyebrow'));
await p.click('text=O serviço terminou');await p.waitForTimeout(300);log('aval serv:',await p.textContent('h1'));});
await step('diaria',async()=>{await p.goto(U+'/');await p.fill('#busca','quintal');await p.click('.cartao >> nth=0');
const d=new Date(Date.now()+10*86400000).toISOString().slice(0,10);await p.fill('#r-checkin',d);await p.click('button:has-text("Confirmar e pagar")');await p.click('text=Gerar Pix');await p.click('text=Simular Pix recebido');await p.waitForURL('**/reserva/**');
await p.click('button:has-text("Cancelar")');log('cancel:',await p.textContent('.alerta'));await p.click('text=Sim, cancelar');await p.waitForTimeout(200);log(await p.textContent('.toast'));});
await step('celus',async()=>{await p.click('nav >> text=Perfil');await p.click('.walletmini');log('celus page:',await p.$$eval('h2',e=>e.map(x=>x.textContent)));});
await step('logout',async()=>{await p.click('nav >> text=Perfil');await p.click('text=Sair da conta');await p.waitForURL('**/entrar');await p.click('text=Já tenho conta');await p.fill('#e-email','emanuelle@x.com');await p.fill('#e-senha','errada123');await p.click('button:has-text("Entrar")');log('login err:',await p.textContent('.erro'));await p.fill('#e-senha','12345678');await p.click('button:has-text("Entrar")');await p.waitForURL(U+'/');log('login ok');});
log('errors',errs);await b.close();})();
