const {chromium}=require('playwright');const S=__dirname,U=process.env.CELUS_URL||'http://localhost:4173';
(async()=>{const b=await chromium.launch();const c=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,geolocation:{latitude:-23.5505,longitude:-46.6333},permissions:['geolocation']});const p=await c.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));p.setDefaultTimeout(8000);
const log=(...a)=>console.log(...a);const O=S+'/../../.teste-saida/';const step=async(n,f)=>{try{await f()}catch(e){log('FAIL',n,e.message.split('\n')[0]);await p.screenshot({path:O+'falha-'+n+'.png'});}};
const cad=async(n,e)=>{await p.goto(U+'/entrar');await p.click('text=Criar conta');await p.fill('#c-nome',n);await p.fill('#c-email',e);await p.fill('#c-senha','12345678');await p.fill('#c-nasc','1990-05-01');await p.check('#c-aceite');await p.click('button:has-text("Continuar")');await p.waitForURL('**/verificar');await p.setInputFiles('#v-doc',S+'/foto.jpg');await p.setInputFiles('#v-selfie',S+'/foto.jpg');await p.click('text=Enviar para verificação');await p.waitForURL(U+'/');};
const saldo=async()=>{await p.goto(U+'/perfil');return (await p.textContent('.walletmini b')).trim();};
const expect=(n,v,w)=>{if(String(v)!==String(w))log('FAIL',n,'esperado',w,'veio',v);else log(n,'ok',v);};
await step('boas-vindas',async()=>{await cad('Rita Lima','rita@x.com');expect('saldo inicial',await saldo(),100);});
await step('comunidade',async()=>{await p.goto(U+'/perfil');await p.click('.entrada:has-text("Comunidades")');await p.waitForSelector('.comu');log('comunidades:',await p.$$eval('.comu b',e=>e.map(x=>x.textContent)));
  await p.click('.comu:has-text("Calistenia")');await p.click('button:has-text("Participar")');await p.waitForTimeout(200);
  await p.click('button:has-text("Confirmar presença (50 celus)")');await p.waitForTimeout(200);log('toast:',await p.textContent('.toast'));
  await p.screenshot({path:O+'comunidade.png',fullPage:true});
  expect('saldo com caução',await saldo(),50);log('guardados:',await p.textContent('.walletmini .hint'));
  await p.goto(U+'/comunidade');await p.click('.comu:has-text("Calistenia")');await p.click('text=Simular conferência do código');await p.waitForTimeout(200);
  expect('caução devolvida',await saldo(),100);});
await step('cancelar fora do prazo',async()=>{await p.goto(U+'/comunidade');await p.click('.comu:has-text("Trilha")');await p.click('button:has-text("Participar")');
  await p.click('button:has-text("Confirmar presença")');await p.waitForTimeout(200);const s1=await saldo();
  await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('celus-db-v1'));const e=d.encontros.find(x=>x.id==='e3');e.prazoCancelH=9999;localStorage.setItem('celus-db-v1',JSON.stringify(d));});
  await p.goto(U+'/comunidade');await p.reload();await p.click('.comu:has-text("Trilha")');await p.click('text=Não vou mais');await p.waitForTimeout(200);
  await p.click('.encontro button:has-text("Cancelar presença")');await p.waitForTimeout(200);log('toast:',await p.textContent('.toast'));
  expect('perdeu caução',await saldo(),s1);});
await step('nova comunidade',async()=>{await p.goto(U+'/comunidade/nova');await p.fill('#nc-nome','Corrida na Enseada');await p.fill('#nc-atv','Corrida');await p.fill('#nc-bairro','Enseada');await p.click('button:has-text("Criar comunidade")');await p.waitForTimeout(300);if(await p.$('.erro'))log('FAIL criar',await p.textContent('.erro'));log('criada:',await p.textContent('h1'));
  await p.click('text=Marcar um encontro');await p.screenshot({path:O+'novo-encontro.png',fullPage:true});});
await step('achados',async()=>{await p.goto(U+'/perfil');await p.click('.entrada:has-text("Feira do Polvo")');await p.waitForSelector('.troca');log('itens:',await p.$$eval('.troca .t',e=>e.map(x=>x.textContent)));
  await p.screenshot({path:O+'achados.png',fullPage:true});
  await p.click('.troca:has-text("Cama")');await p.click('button:has-text("Quero por 40 celus")');await p.waitForTimeout(200);log('codigo:',await p.textContent('.code'));
  await p.click('text=Simular retirada');await p.waitForTimeout(200);log('estado:',await p.textContent('.alerta'));
  const s=Number(await saldo());log('saldo depois da cama',s);
  await p.goto(U+'/trocas');await p.click('.seg >> text=Doações');log('doações:',await p.$$eval('.troca .t',e=>e.map(x=>x.textContent)));});
await step('anunciar item',async()=>{await p.goto(U+'/trocas/nova');await p.setInputFiles('#nt-foto',S+'/foto.jpg');await p.fill('#nt-titulo','Vape usado');await p.click('button:has-text("Publicar")');log('proibido:',await p.textContent('.erro'));
  await p.fill('#nt-titulo','Mudas de espada-de-são-jorge');await p.fill('#nt-preco','10');await p.fill('#nt-bairro','Enseada');await p.click('button:has-text("Publicar")');await p.waitForURL('**/trocas');await p.click('.seg >> text=Minhas');log('minhas:',await p.$$eval('.troca .t',e=>e.map(x=>x.textContent)));});
await step('perfil publico',async()=>{await p.goto(U+'/perfil');await p.screenshot({path:O+'perfil.png',fullPage:true});await p.click('text=Ver como os outros veem');await p.waitForURL('**/pessoa/**');await p.waitForSelector('.avatar');log('blocos:',await p.$$eval('h2',e=>e.map(x=>x.textContent)));
  await p.goto(U+'/perfil');await p.locator('.sumline.priv input').nth(0).uncheck();await p.click('text=Ver como os outros veem');await p.waitForURL('**/pessoa/**');await p.waitForSelector('.avatar');log('blocos sem comunidades:',await p.$$eval('h2',e=>e.map(x=>x.textContent)));});
await step('carteira',async()=>{await p.goto(U+'/celus');await p.waitForSelector('.walletcard');log('h2:',await p.$$eval('h2',e=>e.map(x=>x.textContent)));log('extrato:',await p.$$eval('.sumline span:first-child',e=>e.slice(-6).map(x=>x.textContent.slice(0,50))));});
log('errors',errs);await b.close();})();
