const {chromium}=require('playwright');const S=__dirname,U=process.env.CELUS_URL||'http://localhost:4173';
(async()=>{const b=await chromium.launch();const c=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,geolocation:{latitude:-23.5505,longitude:-46.6333},permissions:['geolocation']});const p=await c.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));p.setDefaultTimeout(8000);
const log=(...a)=>console.log(...a);const O=S+'/../../.teste-saida/';const step=async(n,f)=>{try{await f()}catch(e){log('FAIL',n,e.message.split('\n')[0]);await p.screenshot({path:O+'falha-'+n+'.png'});}};
const cad=async(n,e)=>{await p.goto(U+'/entrar');await p.click('text=Criar conta');await p.fill('#c-nome',n);await p.fill('#c-email',e);await p.fill('#c-senha','12345678');await p.fill('#c-nasc','1990-05-01');await p.check('#c-aceite');await p.click('button:has-text("Continuar")');await p.waitForURL('**/verificar');await p.setInputFiles('#v-doc',S+'/foto.jpg');await p.setInputFiles('#v-selfie',S+'/foto.jpg');await p.click('text=Enviar para verificação');await p.waitForURL(U+'/');};
const saldo=async()=>{await p.goto(U+'/perfil');return Number((await p.textContent('.walletmini b')).trim());};
const expect=(n,v,w)=>{if(String(v)!==String(w))log('FAIL',n,'esperado',w,'veio',v);else log(n,'ok',v);};
const db=(f)=>p.evaluate(f);
await step('ranking pessoas',async()=>{await cad('Rita Lima','rita@x.com');await p.goto(U+'/perfil');await p.click('text=Ranking');await p.waitForURL('**/ranking');
  await p.waitForSelector('.rk-linha.voce');log('linhas:',await p.locator('.rk-linha').count());log('você:',(await p.textContent('.rk-linha.voce')).trim());
  expect('pódio com 3',await p.locator('.podio-lugar').count(),3);await p.click('.seg >> text=Mês');await p.waitForSelector('.rk-linha.voce');await p.screenshot({path:O+'ranking.png',fullPage:true});});
await step('adesao comercio',async()=>{const antes=await saldo();await p.check('.sumline.check input');
  await p.goto(U+'/renda');await p.click('text=Tem academia, estúdio ou box?');await p.fill('#ls-nome','Academia da Rita');await p.fill('#ls-bairro','Enseada');await p.click('text=Enviar para aprovação');await p.waitForTimeout(200);
  await p.goto(U+'/renda/curadoria');await p.click('.box:has-text("Academia da Rita") >> button:has-text("Aprovar")');
  expect('bônus de adesão',await saldo()-antes,100);
  await p.goto(U+'/ranking');await p.waitForSelector('.rk-linha.voce');expect('aba comércios',(await p.textContent('.rk-linha.voce .rk-nome')).includes('Academia da Rita'),true);
  await p.goto(U+'/renda/curadoria');await p.goto(U+'/perfil');});
const IDS=['polvo','tubarao','golfinho','baleia','jubarte','tartaruga','caranguejo','lula','palhaco','sardinha','baiacu','lagosta','foca','camarao','ostra','concha','pinguim','lontra','sereia','ancora','onda','veleiro','navio','ilha','coqueiro','tridente','bussola','redemoinho','surfista','lua'];
const NOMES={polvo:'Polvo',tubarao:'Tubarão',golfinho:'Golfinho',baleia:'Baleia',jubarte:'Jubarte',tartaruga:'Tartaruga',caranguejo:'Caranguejo',lula:'Lula',palhaco:'Peixe-palhaço',sardinha:'Sardinha',baiacu:'Baiacu',lagosta:'Lagosta',foca:'Foca',camarao:'Camarão',ostra:'Ostra',concha:'Concha',pinguim:'Pinguim',lontra:'Lontra',sereia:'Sereia',ancora:'Âncora',onda:'Onda',veleiro:'Veleiro',navio:'Navio',ilha:'Ilha',coqueiro:'Coqueiro',tridente:'Tridente',bussola:'Bússola',redemoinho:'Redemoinho',surfista:'Surfista',lua:'Lua cheia'};
const cod=(seg,j)=>{let h=2166136261;for(const ch of `${seg}:${j}`){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0)%1000000;};
const resultado=(dia)=>{const s=[];for(let k=0;s.length<3;k++){const e=IDS[cod('loteria-do-mar:'+dia,k)%30];if(!s.includes(e))s.push(e);}return s;};
const jogar=async(ids)=>{for(const x of ids)await p.click(`.lot-bicho[aria-label="${NOMES[x]}"]`);await p.click('button:has-text("Jogar por")');await p.waitForTimeout(150);};
await step('loteria',async()=>{const antes=await saldo();await p.click('text=Loteria do Mar');await p.waitForURL('**/loteria');
  await p.waitForSelector('.lot-concurso');expect('concursos iniciais',await p.locator('.lot-concurso').count(),3);log('prêmio:',(await p.textContent('.lot-premio-valor')).trim());
  await jogar(['polvo','tubarao','baleia']);await jogar(['polvo','tubarao','baleia']);log('repetido:',await p.textContent('.erro'));
  const dia=await db(()=>JSON.parse(localStorage.getItem('celus-db-v1')).bilhetes[0].dia);const win=resultado(dia);log('concurso',dia,'vai sair',win.join(','));
  await p.click('button:has-text("Jogar por")').catch(()=>{});await p.goto(U+'/loteria');
  await jogar(win);const outro=IDS.find(x=>!win.includes(x));await jogar([win[0],win[1],outro]);
  await p.click('text=Surpresinha');await p.click('button:has-text("Jogar por")');await p.waitForTimeout(150);await p.click('text=Surpresinha');await p.click('button:has-text("Jogar por")');await p.waitForTimeout(150);
  expect('5 bilhetes',await p.locator('.lot-bilhete').count(),5);await p.click('text=Surpresinha');expect('6º bloqueado',await p.isDisabled('button:has-text("Jogar por")'),true);
  await p.screenshot({path:O+'loteria.png',fullPage:true});
  await p.click('text=Adiantar o sorteio (teste)');await p.waitForURL('**/loteria/ao-vivo**');await p.waitForSelector('.lot-slot.saiu',{timeout:16000});await p.screenshot({path:O+'ao-vivo.png',fullPage:true});
  const r=await db(()=>{const d=JSON.parse(localStorage.getItem('celus-db-v1'));return {b:d.bilhetes.map(x=>[x.escolha.join(','),x.status,x.acertos,x.premio||0]),l:d.loteria};});
  log('bilhetes:',JSON.stringify(r.b));log('concurso:',JSON.stringify(r.l.concursos[0]));
  expect('saiu o previsto',r.l.concursos[0].saiu.join(','),win.join(','));expect('ganhou o principal',r.b.find(x=>x[0]===win.join(','))[1],'ganhou');
  expect('2 acertos paga 20',r.b.find(x=>x[0]===[win[0],win[1],outro].join(','))[3],20);expect('volta ao inicial',r.l.acumulado,800);
  const premios=r.b.reduce((s,x)=>s+x[3],0);expect('saldo da loteria',await saldo()-antes,premios-50);
  await p.goto(U+'/ranking');log('pontos no ranking (sem loteria):',await p.textContent('.rk-linha.voce .rk-pts'));});
await step('coroacao',async()=>{const antes=await saldo();
  await db(()=>{const d=JSON.parse(localStorage.getItem('celus-db-v1'));const uid=d.sessao;d.carteiras[uid].hist.push({t:Date.now()-7*86400000,txt:'Teste semana passada',v:5000,k:'reserva'});d.premiacoes=d.premiacoes.filter(k=>!k.startsWith('semana:'));localStorage.setItem('celus-db-v1',JSON.stringify(d));});
  await p.goto(U+'/ranking');await p.reload();await p.waitForSelector('.podio');
  expect('prêmio 1º da semana',await saldo()-antes,50);
  await p.goto(U+'/ranking');expect('campeão no pódio',(await p.textContent('.podio-lugar.p1')).includes('Academia da Rita'),true);
  await p.reload();expect('não paga duas vezes',await saldo()-antes,50);});
log('errors',errs);await b.close();})();
