const {chromium}=require('playwright');const S=__dirname,U=process.env.CELUS_URL||'http://localhost:4173';
(async()=>{const b=await chromium.launch();const c=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,geolocation:{latitude:-23.5505,longitude:-46.6333},permissions:['geolocation']});const p=await c.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));p.setDefaultTimeout(8000);
const log=(...a)=>console.log(...a);const O=S+'/../../.teste-saida/';const step=async(n,f)=>{try{await f()}catch(e){log('FAIL',n,e.message.split('\n')[0]);await p.screenshot({path:O+'falha-'+n+'.png'});}};
const cad=async(n,e)=>{await p.goto(U+'/entrar');await p.click('text=Criar conta');await p.fill('#c-nome',n);await p.fill('#c-email',e);await p.fill('#c-senha','12345678');await p.fill('#c-nasc','1990-05-01');await p.check('#c-aceite');await p.click('button:has-text("Continuar")');await p.waitForURL('**/verificar');await p.setInputFiles('#v-doc',S+'/foto.jpg');await p.setInputFiles('#v-selfie',S+'/foto.jpg');await p.click('text=Enviar para verificação');await p.waitForURL(U+'/');};
const sair=async()=>{await p.goto(U+'/perfil');await p.click('text=Sair da conta');await p.waitForURL('**/entrar');};
const entrar=async(e)=>{await p.click('text=Já tenho conta');await p.fill('#e-email',e);await p.fill('#e-senha','12345678');await p.click('button:has-text("Entrar")');await p.waitForURL(U+'/');};
const saldo=async()=>{await p.goto(U+'/perfil');return Number((await p.textContent('.walletmini b')).trim());};
const expect=(n,v,w)=>{if(String(v)!==String(w))log('FAIL',n,'esperado',w,'veio',v);else log(n,'ok',v);};
await step('treino demo',async()=>{await cad('Lia Souza','lia@x.com');await p.goto(U+'/perfil');await p.waitForSelector('.saude-card');log('cartão:',await p.textContent('.saude-card .hint'));
  await p.click('.saude-card');await p.click('.parceiro:has-text("Academia Fôlego") >> text=Simular QR (teste)');await p.waitForSelector('.treino-ok');log('ok:',await p.textContent('.treino-ok'));
  await p.click('.parceiro:has-text("Box Maré Alta") >> text=Simular QR (teste)');await p.waitForTimeout(200);log('segundo no dia:',await p.textContent('.alerta.bad'));
  await p.screenshot({path:O+'saude.png',fullPage:true});expect('saldo',await saldo(),105);});
await step('bonus semana',async()=>{await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('celus-db-v1'));const uid=d.sessao;const now=Date.now();
  // dois treinos anteriores nesta mesma semana (ou no mesmo mês) para testar o bônus
  const ontem=new Date();ontem.setHours(12,0,0,0);ontem.setDate(ontem.getDate()-1);const anteontem=new Date(ontem);anteontem.setDate(anteontem.getDate()-1);
  d.checkinsSaude=d.checkinsSaude.filter(x=>x.userId!==uid);d.checkinsSaude.push({id:'x1',userId:uid,localId:'h1',t:anteontem.getTime()},{id:'x2',userId:uid,localId:'h1',t:ontem.getTime()});
  const c=d.carteiras[uid];c.hoje.contagem.treino=0;localStorage.setItem('celus-db-v1',JSON.stringify(d));});
  await p.goto(U+'/saude');await p.reload();const dow=new Date().getDay();await p.click('.parceiro:has-text("Academia Fôlego") >> text=Simular QR (teste)');await p.waitForSelector('.treino-ok');log('com bônus?',await p.textContent('.treino-ok'),'(dia da semana',dow,')');});
await step('parceiro',async()=>{await sair();await cad('Caio Fôlego','caio@x.com');await p.goto(U+'/perfil');await p.check('.sumline.check input');
  await p.goto(U+'/renda');await p.click('text=Tem academia, estúdio ou box?');await p.fill('#ls-nome','Academia Teste');await p.fill('#ls-bairro','Enseada');await p.click('text=Enviar para aprovação');await p.waitForTimeout(200);log('pendente:',await p.textContent('.alerta.warn'));
  await p.goto(U+'/renda/curadoria');await p.click('.box:has-text("Academia Teste") >> button:has-text("Aprovar")');await p.goto(U+'/renda/saude');await p.waitForSelector('.qr svg');await p.screenshot({path:O+'qr.png'});
  const cod=(await p.textContent('.qr-cod')).replace(/\D/g,'');const lid=await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('celus-db-v1'));return d.locaisSaude.find(l=>l.nome==='Academia Teste').id;});
  await p.goto(U+`/saude/checkin?l=${lid}&c=${cod}`);await p.waitForSelector('.alerta, .treino-ok');log('dono:',await p.textContent('.alerta'));
  await sair();await p.goto(U+`/saude/checkin?l=${lid}&c=${cod}`);await p.waitForURL('**/entrar');await p.click('text=Já tenho conta');await p.fill('#e-email','lia@x.com');await p.fill('#e-senha','12345678');await p.click('button:has-text("Entrar")');await p.waitForURL('**/saude/checkin**');log('voltou para o QR depois do login');await p.waitForSelector('.alerta, .treino-ok');
  await c.setGeolocation({latitude:-23.60,longitude:-46.70});await p.goto(U+`/saude/checkin?l=${lid}&c=${cod}`);await p.waitForSelector('.alerta, .treino-ok');log('longe:',await p.textContent('.alerta'));
  await c.setGeolocation({latitude:-23.5505,longitude:-46.6333});await p.goto(U+`/saude/checkin?l=${lid}&c=999999`);await p.waitForSelector('.alerta, .treino-ok');log('código errado:',await p.textContent('.alerta'));
  await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('celus-db-v1'));const uid=d.sessao;d.checkinsSaude=d.checkinsSaude.filter(x=>!(x.userId===uid&&new Date(x.t).toDateString()===new Date().toDateString()));d.carteiras[uid].hoje.contagem.treino=0;localStorage.setItem('celus-db-v1',JSON.stringify(d));});
  await p.goto(U+`/saude/checkin?l=${lid}&c=${cod}`);await p.waitForSelector('.alerta, .treino-ok');log('real:',await p.textContent('.treino-ok, .alerta'));});
log('errors',errs);await b.close();})();
